### ISSUE TITLE
 Chrome Extension Crashes Tab When Activating Feature 1

### ISSUE THREAD

**Issue by MysteryFlask** [Potato-Development/not-so-securly#3]
Description
The Chrome extension crashes the active tab whenever Feature 1 is activated. This issue occurs consistently and renders the extension unusable for its primary function.

Steps to Reproduce
Install the Chrome extension from the Web Store.
Navigate to any webpage.
Click on the extension icon in the toolbar.
Activate Feature 1 from the extension's popup menu.
Expected Behavior
The extension should perform the actions related to Feature 1 without causing the tab to crash.

Actual Behavior
Activating Feature 1 causes the current tab to crash and display the "Aw, Snap!" error message.

Environment
Extension Version: 1.4.2
Chrome Version: 113.0.5672.127 (Official Build) (64-bit)
OS: Windows 10 Pro, Version 22H2, Build 19045.2965
Additional Information
The issue does not occur when other features are activated.
Console log shows the following error before the tab crashes:
javascript
Copy code
Uncaught TypeError: Cannot read properties of undefined (reading 'initFeatureX')
    at Object.activateFeatureX (content.js:214)
    at HTMLButtonElement.<anonymous> (popup.js:89)
Reinstalling the extension and resetting Chrome settings did not resolve the issue.

**Comment by edamame-maru** [comment]
Thank you for bringing this issue to our attention. We apologize for the inconvenience caused by the crashing of the active tab when Feature 1 is activated. Our development team is actively investigating the error in the console log to identify and fix the root cause. In the meantime, we recommend avoiding activating Feature 1 and utilizing other features of the extension. Your patience and understanding are greatly appreciated as we work to resolve this issue promptly.
